tenant: scouredimage
app: demoapp
service: demo-service

custom:
  enterprise:
    logIngestMode: pull

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128
  timeout: 15

functions:
  hello:
    handler: handler.hello
    timeout: 15
    events:
      - http:
          path: hello
          method: post

