tenant: scouredimage
app: demoapp
service: demo-service

custom:
  region:
    black: us-west-1
    white: us-east-2
    red: eu-west-1

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 15

functions:
  hello:
    handler: handler.hello
    timeout: 15
    events:
      - http:
          path: hello
          method: post

