tenant: scouredimage
app: demoapp
service: demo-service

plugins:
  - '@serverless/enterprise-plugin'

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  memorySize: 128
  timeout: 8

functions:
  hello:
    handler: handler.hello
    
    events:
      - http:
          path: hello
          method: post

